In [3]:
### What we want: get indexes from each industry and use their returns for fitting and showing a copula for the normal and t distributions

# This will eliminate survivorship bias, as these indices will be around for a while and don't die during market crashes

# will use training data from the mid 2000s to create a copula before the 2008 crash. Will do the same for 2020 and 2001
    # will then compare these results and what the normal and t copulas dictate in these scenarios

In [4]:
import yfinance as yf
import sys
import pandas as pd
import numpy as np
from scipy.stats import t, multivariate_t, norm
sys.path.append("/Users/willneuner/Desktop/FINTECH545")

In [5]:
yahoo_tickers = {
    # Sectors / Industries
    "Technology": "XLK",
    "Financials": "XLF",
    "Energy": "XLE",
    "Healthcare": "XLV",
    "Industrials": "XLI",
    "Utilities": "XLU",
    "Consumer Discretionary": "XLY",
    "Consumer Staples": "XLP",
    "Materials": "XLB",
    "Real Estate": "XLRE",
    "Communication Services": "XLC",

    # Commodities
    "Broad Commodities": "DBC",
    "Crude Oil": "USO",
    "Gold": "GLD",
    # "Silver": "SLV",
    "Natural Gas": "UNG",
    "Agriculture": "DBA",

    # FX / Currencies
    "US Dollar Index": "UUP",
    "EUR/USD": "FXE",
    # "GBP/USD": "FXB",
    "JPY/USD": "FXY",
    # "CAD/USD": "FXC"
}

In [6]:
ticker = yahoo_tickers['Technology']
tickers = list(yahoo_tickers.values())
data = yf.download(tickers = tickers, period="5y", interval="1d")

/var/folders/1d/dkqlxg7d3yv8ccfw3vkrtnsm0000gn/T/ipykernel_22815/2551565624.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(tickers = tickers, period="5y", interval="1d")
[*********************100%***********************]  19 of 19 completed

In [7]:
from risk_management.measurements import compute_correlation, compute_covariance, compute_returns
from risk_management.goodness_of_fit import log_likelihood

In [8]:
returns = compute_returns(data['Close'])

In [9]:
corr = compute_correlation(returns)

In [10]:
corr

Ticker,DBA,DBC,FXE,FXY,GLD,UNG,USO,UUP,XLB,XLC,XLE,XLF,XLI,XLK,XLP,XLRE,XLU,XLV,XLY
Ticker,,,,,,,,,,,,,,,,,,,
DBA,1.000000,0.446488,0.123941,0.033445,0.175158,0.093902,0.289610,-0.148966,0.214947,0.128224,0.258830,0.159766,0.174615,0.141578,0.075373,0.110167,0.054879,0.063100,0.120617
DBC,0.446488,1.000000,0.135353,0.031474,0.338342,0.248376,0.919956,-0.184628,0.306626,0.152423,0.658966,0.215338,0.260127,0.183917,0.083881,0.135274,0.123550,0.080194,0.157161
FXE,0.123941,0.135353,1.000000,0.481657,0.414726,-0.001358,0.039723,-0.957535,0.336415,0.209672,0.103003,0.213290,0.223460,0.198951,0.230739,0.277981,0.170067,0.214029,0.223511
FXY,0.033445,0.031474,0.481657,1.000000,0.394661,-0.026032,-0.040131,-0.629276,0.057531,0.004424,-0.058370,-0.086771,-0.044254,-0.048293,0.094881,0.141682,0.125457,0.054295,-0.022056
GLD,0.175158,0.338342,0.414726,0.394661,1.000000,0.030950,0.193884,-0.474101,0.228391,0.099989,0.157851,0.029379,0.110143,0.112967,0.122030,0.191078,0.226096,0.107790,0.064076
UNG,0.093902,0.248376,-0.001358,-0.026032,0.030950,1.000000,0.130612,-0.016773,0.120766,0.071277,0.187227,0.100100,0.091959,0.084787,0.057966,0.090175,0.085491,0.082941,0.082526
USO,0.289610,0.919956,0.039723,-0.040131,0.193884,0.130612,1.000000,-0.073732,0.225619,0.107065,0.656849,0.186242,0.212370,0.126925,0.037205,0.080929,0.071756,0.037041,0.103066
UUP,-0.148966,-0.184628,-0.957535,-0.629276,-0.474101,-0.016773,-0.073732,1.000000,-0.373373,-0.238278,-0.139347,-0.225479,-0.247694,-0.218744,-0.262152,-0.322262,-0.217418,-0.241660,-0.248575
XLB,0.214947,0.306626,0.336415,0.057531,0.228391,0.120766,0.225619,-0.373373,1.000000,0.615750,0.548355,0.791578,0.855675,0.627099,0.563214,0.650546,0.482160,0.622953,0.677872
XLC,0.128224,0.152423,0.209672,0.004424,0.099989,0.071277,0.107065,-0.238278,0.615750,1.000000,0.294349,0.631177,0.658056,0.779979,0.423903,0.532171,0.339792,0.512766,0.774317
XLE,0.258830,0.658966,0.103003,-0.058370,0.157851,0.187227,0.656849,-0.139347,0.548355,0.294349,1.000000,0.544728,0.536141,0.294961,0.246497,0.294336,0.243991,0.282308,0.319183
XLF,0.159766,0.215338,0.213290,-0.086771,0.029379,0.100100,0.186242,-0.225479,0.791578,0.631177,0.544728,1.000000,0.845794,0.599582,0.537712,0.591631,0.445363,0.592446,0.674851
XLI,0.174615,0.260127,0.223460,-0.044254,0.110143,0.091959,0.212370,-0.247694,0.855675,0.658056,0.536141,0.845794,1.000000,0.706799,0.551046,0.650329,0.503846,0.617777,0.735279
XLK,0.141578,0.183917,0.198951,-0.048293,0.112967,0.084787,0.126925,-0.218744,0.627099,0.779979,0.294961,0.599582,0.706799,1.000000,0.359912,0.513502,0.315837,0.509846,0.808312
XLP,0.075373,0.083881,0.230739,0.094881,0.122030,0.057966,0.037205,-0.262152,0.563214,0.423903,0.246497,0.537712,0.551046,0.359912,1.000000,0.614030,0.611354,0.649506,0.440946
XLRE,0.110167,0.135274,0.277981,0.141682,0.191078,0.090175,0.080929,-0.322262,0.650546,0.532171,0.294336,0.591631,0.650329,0.513502,0.614030,1.000000,0.666061,0.624496,0.576409
XLU,0.054879,0.123550,0.170067,0.125457,0.226096,0.085491,0.071756,-0.217418,0.482160,0.339792,0.243991,0.445363,0.503846,0.315837,0.611354,0.666061,1.000000,0.521761,0.340862
XLV,0.063100,0.080194,0.214029,0.054295,0.107790,0.082941,0.037041,-0.241660,0.622953,0.512766,0.282308,0.592446,0.617777,0.509846,0.649506,0.624496,0.521761,1.000000,0.511989
XLY,0.120617,0.157161,0.223511,-0.022056,0.064076,0.082526,0.103066,-0.248575,0.677872,0.774317,0.319183,0.674851,0.735279,0.808312,0.440946,0.576409,0.340862,0.511989,1.000000

In [11]:
cov = compute_covariance(returns)

In [12]:
cov

Ticker,DBA,DBC,FXE,FXY,GLD,UNG,USO,UUP,XLB,XLC,XLE,XLF,XLI,XLK,XLP,XLRE,XLU,XLV,XLY
Ticker,,,,,,,,,,,,,,,,,,,
DBA,0.000083,0.000048,5.442184e-06,1.921879e-06,0.000016,3.291212e-05,0.000055,-0.000006,0.000023,1.540513e-05,0.000040,0.000017,0.000017,0.000020,0.000006,0.000012,0.000005,0.000005,0.000016
DBC,0.000048,0.000140,7.722215e-06,2.349960e-06,0.000039,1.131106e-04,0.000227,-0.000010,0.000043,2.379366e-05,0.000132,0.000030,0.000033,0.000034,0.000008,0.000019,0.000016,0.000009,0.000028
FXE,0.000005,0.000008,2.332955e-05,1.470557e-05,0.000020,-2.527955e-07,0.000004,-0.000021,0.000019,1.338395e-05,0.000008,0.000012,0.000012,0.000015,0.000009,0.000016,0.000009,0.000009,0.000016
FXY,0.000002,0.000002,1.470557e-05,3.995593e-05,0.000024,-6.344154e-06,-0.000005,-0.000018,0.000004,3.695404e-07,-0.000006,-0.000007,-0.000003,-0.000005,0.000005,0.000011,0.000009,0.000003,-0.000002
GLD,0.000016,0.000039,1.958385e-05,2.438924e-05,0.000096,1.166588e-05,0.000040,-0.000021,0.000027,1.291897e-05,0.000026,0.000003,0.000012,0.000017,0.000010,0.000023,0.000024,0.000010,0.000009
UNG,0.000033,0.000113,-2.527955e-07,-6.344154e-06,0.000012,1.486433e-03,0.000105,-0.000003,0.000056,3.631742e-05,0.000122,0.000046,0.000038,0.000051,0.000018,0.000042,0.000036,0.000029,0.000048
USO,0.000055,0.000227,4.004088e-06,-5.293965e-06,0.000040,1.050908e-04,0.000436,-0.000007,0.000056,2.952882e-05,0.000233,0.000046,0.000048,0.000041,0.000006,0.000020,0.000016,0.000007,0.000032
UUP,-0.000006,-0.000010,-2.095929e-05,-1.802604e-05,-0.000021,-2.930648e-06,-0.000007,0.000021,-0.000020,-1.427065e-05,-0.000011,-0.000012,-0.000012,-0.000015,-0.000010,-0.000018,-0.000011,-0.000010,-0.000017
XLB,0.000023,0.000043,1.941415e-05,4.344910e-06,0.000027,5.562981e-05,0.000056,-0.000020,0.000143,9.722675e-05,0.000111,0.000113,0.000111,0.000116,0.000055,0.000094,0.000063,0.000068,0.000122
XLC,0.000015,0.000024,1.338395e-05,3.695404e-07,0.000013,3.631742e-05,0.000030,-0.000014,0.000097,1.746556e-04,0.000066,0.000099,0.000094,0.000160,0.000046,0.000085,0.000049,0.000062,0.000154
XLE,0.000040,0.000132,8.438831e-06,-6.258375e-06,0.000026,1.224391e-04,0.000233,-0.000011,0.000111,6.598300e-05,0.000288,0.000110,0.000099,0.000078,0.000034,0.000060,0.000045,0.000044,0.000081
XLF,0.000017,0.000030,1.227058e-05,-6.532939e-06,0.000003,4.596733e-05,0.000046,-0.000012,0.000113,9.935386e-05,0.000110,0.000142,0.000109,0.000111,0.000053,0.000085,0.000058,0.000064,0.000121
XLI,0.000017,0.000033,1.169249e-05,-3.030392e-06,0.000012,3.840794e-05,0.000048,-0.000012,0.000111,9.421259e-05,0.000099,0.000109,0.000117,0.000119,0.000049,0.000085,0.000059,0.000061,0.000120
XLK,0.000020,0.000034,1.492760e-05,-4.742006e-06,0.000017,5.078000e-05,0.000041,-0.000015,0.000116,1.601272e-04,0.000078,0.000111,0.000119,0.000241,0.000046,0.000096,0.000053,0.000072,0.000188
XLP,0.000006,0.000008,9.143312e-06,4.920401e-06,0.000010,1.833475e-05,0.000006,-0.000010,0.000055,4.596083e-05,0.000034,0.000053,0.000049,0.000046,0.000067,0.000061,0.000055,0.000049,0.000054
XLRE,0.000012,0.000019,1.624061e-05,1.083274e-05,0.000023,4.205254e-05,0.000020,-0.000018,0.000094,8.506984e-05,0.000060,0.000085,0.000085,0.000096,0.000061,0.000146,0.000088,0.000069,0.000105
XLU,0.000005,0.000016,8.942891e-06,8.633552e-06,0.000024,3.588379e-05,0.000016,-0.000011,0.000063,4.888888e-05,0.000045,0.000058,0.000059,0.000053,0.000055,0.000088,0.000119,0.000052,0.000056
XLV,0.000005,0.000009,9.417322e-06,3.126473e-06,0.000010,2.913010e-05,0.000007,-0.000010,0.000068,6.173232e-05,0.000044,0.000064,0.000061,0.000072,0.000049,0.000069,0.000052,0.000083,0.000070
XLY,0.000016,0.000028,1.620263e-05,-2.092470e-06,0.000009,4.775261e-05,0.000032,-0.000017,0.000122,1.535833e-04,0.000081,0.000121,0.000120,0.000188,0.000054,0.000105,0.000056,0.000070,0.000225

In [13]:
U = pd.DataFrame([{"A": 0.2, "B":0.3}, {"A": 0.4, "B":0.6}, {"A": 0.4, "B":0.9}, {"A": 0.99, "B":0.1}])
LLs = []
for v in [2, 3, 4, 5, 7, 9, 12, 16, 20, 25, 30, 36, 42, 50]:
    T = t.ppf(U, df=v)
    print("DF:", v)
    corr = compute_correlation(pd.DataFrame(T), method="pearson")
    print("CORR:", corr)
    t_params = {"loc": np.zeros(corr.shape[0]), "shape": corr, "df":v}
    LL = log_likelihood(multivariate_t.pdf, t_params, T)
    print("LL:", LL)
    LLs.append((LL, v))

DF: 2
CORR:           0         1
0  1.000000 -0.705583
1 -0.705583  1.000000
LL: -18.303870124825337
DF: 3
CORR:          0        1
0  1.00000 -0.67654
1 -0.67654  1.00000
LL: -15.889956769112231
DF: 4
CORR:           0         1
0  1.000000 -0.660923
1 -0.660923  1.000000
LL: -14.70281006598284
DF: 5
CORR:           0         1
0  1.000000 -0.651443
1 -0.651443  1.000000
LL: -14.007302830130751
DF: 7
CORR:           0         1
0  1.000000 -0.640672
1 -0.640672  1.000000
LL: -13.234756120809113
DF: 9
CORR:          0        1
0  1.00000 -0.63477
1 -0.63477  1.00000
LL: -12.818038008599355
DF: 12
CORR:          0        1
0  1.00000 -0.62968
1 -0.62968  1.00000
LL: -12.461651856986963
DF: 16
CORR:           0         1
0  1.000000 -0.625917
1 -0.625917  1.000000
LL: -12.199730376598083
DF: 20
CORR:           0         1
0  1.000000 -0.623685
1 -0.623685  1.000000
LL: -12.04486718556257
DF: 25
CORR:           0         1
0  1.000000 -0.621913
1 -0.621913  1.000000
LL: -11.92223804235335
DF: 30
CORR:          0        1
0  1.00000 -0.62074
1 -0.62074  1.00000
LL: -11.841115011145494
DF: 36
CORR:           0         1
0  1.000000 -0.619767
1 -0.619767  1.000000
LL: -11.773900000522893
DF: 42
CORR:           0         1
0  1.000000 -0.619074
1 -0.619074  1.000000
LL: -11.726105898911676
DF: 50
CORR:           0         1
0  1.000000 -0.618412
1 -0.618412  1.000000
LL: -11.68039391953555

In [14]:
max(LLs)

(np.float64(-11.68039391953555), 50)

### Playing with the Gaussian Copula

In [15]:
from copulae.elliptical import GaussianCopula as copulae_g
from statsmodels.distributions.copula.api import GaussianCopula as sm_g

In [16]:
g_copula = copulae_g(dim=19)
g_copula.fit(U, to_pobs=False, method="ml", verbose=1000)

InputDataError: Dimension of data does not match copula

In [ ]:
rho_mat = g_copula.params
g_corr = construct_corr_from_rhos(dim=19, rho_array=rho_mat)

In [ ]:
g_copula.random(1)

NameError: name 'g_copula' is not defined

In [ ]:
# g_copula.sigma -> same as g_corr
g_copula.cdf(np.random.rand(19))

8.675120289083417e-29

In [ ]:
mask = ~np.eye(g_corr.shape[0], dtype=bool)
off_diag_indices = np.argwhere(mask)
max_idx = g_corr[mask].argmax()
i, j = off_diag_indices[max_idx]
g_corr[i, j]

np.float64(0.9141865699893618)

In [ ]:
g_corr

array([[ 1.        ,  0.44542248,  0.1128978 ,  0.0216103 ,  0.16510532,
         0.09167549,  0.28025041, -0.13930141,  0.20928074,  0.1150262 ,
         0.24443808,  0.15496742,  0.16034499,  0.12635351,  0.05906388,
         0.09772575,  0.04624597,  0.05295227,  0.11257122],
       [ 0.44542248,  1.        ,  0.11733405,  0.00673382,  0.3242407 ,
         0.24775971,  0.91418657, -0.16721317,  0.29883015,  0.14595918,
         0.6620589 ,  0.21044169,  0.24087309,  0.16890944,  0.05906618,
         0.10769307,  0.0975625 ,  0.05627586,  0.14651778],
       [ 0.1128978 ,  0.11733405,  1.        ,  0.41268768,  0.39143534,
        -0.02999757,  0.02571832, -0.95115659,  0.31746512,  0.21073621,
         0.09363513,  0.22218505,  0.22873439,  0.1997484 ,  0.207295  ,
         0.24654639,  0.12855506,  0.21964918,  0.22000047],
       [ 0.0216103 ,  0.00673382,  0.41268768,  1.        ,  0.39473384,
        -0.04263989, -0.06266785, -0.57059573,  0.01884235, -0.02104834,
        -0.08424248, -0.11690992, -0.06873652, -0.07669488,  0.0784734 ,
         0.11893732,  0.10501927,  0.03972846, -0.04567498],
       [ 0.16510532,  0.3242407 ,  0.39143534,  0.39473384,  1.        ,
         0.0221188 ,  0.17723445, -0.46211705,  0.21073914,  0.08696165,
         0.14499688,  0.02007428,  0.09361875,  0.08681571,  0.10355294,
         0.16960678,  0.20937184,  0.09714055,  0.04420554],
       [ 0.09167549,  0.24775971, -0.02999757, -0.04263989,  0.0221188 ,
         1.        ,  0.12787943,  0.00881496,  0.11105532,  0.05827506,
         0.18009463,  0.08928815,  0.08264981,  0.07691322,  0.05496339,
         0.08142965,  0.07996803,  0.07326144,  0.07732877],
       [ 0.28025041,  0.91418657,  0.02571832, -0.06266785,  0.17723445,
         0.12787943,  1.        , -0.05878274,  0.21203911,  0.09773437,
         0.65994213,  0.17483535,  0.1890454 ,  0.10608655,  0.01429686,
         0.05467236,  0.05067523,  0.0154035 ,  0.0894682 ],
       [-0.13930141, -0.16721317, -0.95115659, -0.57059573, -0.46211705,
         0.00881496, -0.05878274,  1.        , -0.35594534, -0.23547581,
        -0.12286756, -0.22896758, -0.2492696 , -0.21633768, -0.24125366,
        -0.29125852, -0.17594618, -0.24000385, -0.24201468],
       [ 0.20928074,  0.29883015,  0.31746512,  0.01884235,  0.21073914,
         0.11105532,  0.21203911, -0.35594534,  1.        ,  0.58900183,
         0.52390714,  0.77496208,  0.84402117,  0.59002643,  0.5423272 ,
         0.62961255,  0.45373092,  0.60198355,  0.6508519 ],
       [ 0.1150262 ,  0.14595918,  0.21073621, -0.02104834,  0.08696165,
         0.05827506,  0.09773437, -0.23547581,  0.58900183,  1.        ,
         0.26212686,  0.61330297,  0.63521996,  0.77217863,  0.40245507,
         0.50937334,  0.31864917,  0.49888758,  0.76477235],
       [ 0.24443808,  0.6620589 ,  0.09363513, -0.08424248,  0.14499688,
         0.18009463,  0.65994213, -0.12286756,  0.52390714,  0.26212686,
         1.        ,  0.5267865 ,  0.50866139,  0.24744166,  0.21670845,
         0.26294786,  0.22260376,  0.24938031,  0.28212671],
       [ 0.15496742,  0.21044169,  0.22218505, -0.11690992,  0.02007428,
         0.08928815,  0.17483535, -0.22896758,  0.77496208,  0.61330297,
         0.5267865 ,  1.        ,  0.8336156 ,  0.56328161,  0.52320946,
         0.58022286,  0.42188815,  0.57511715,  0.65210409],
       [ 0.16034499,  0.24087309,  0.22873439, -0.06873652,  0.09361875,
         0.08264981,  0.1890454 , -0.2492696 ,  0.84402117,  0.63521996,
         0.50866139,  0.8336156 ,  1.        ,  0.67262111,  0.52832997,
         0.63703011,  0.48319187,  0.60157965,  0.71092403],
       [ 0.12635351,  0.16890944,  0.1997484 , -0.07669488,  0.08681571,
         0.07691322,  0.10608655, -0.21633768,  0.59002643,  0.77217863,
         0.24744166,  0.56328161,  0.67262111,  1.        ,  0.32224133,
         0.47994392,  0.27948881,  0.48609668,  0.78984192],
       [ 0.05906388,  0.05906618,  0.207295  ,  0.0784734 ,  0.10355294,
         0.05496339,  0.01429686, -0.24125366,  0.5423272 ,  0.40245507,
         0.21670845,  0.52320946,  0.52832997,  0.32224133,  1.        ,
         0.61365161,  0.6106914 ,  0.63538472,  0.40755735],
       [ 0.09772575,  0.10769307,  0.24654639,  0.11893732,  0.16960678,
         0.08142965,  0.05467236, -0.29125852,  0.62961255,  0.50937334,
         0.26294786,  0.58022286,  0.63703011,  0.47994392,  0.61365161,
         1.        ,  0.65068584,  0.62336804,  0.54514796],
       [ 0.04624597,  0.0975625 ,  0.12855506,  0.10501927,  0.20937184,
         0.07996803,  0.05067523, -0.17594618,  0.45373092,  0.31864917,
         0.22260376,  0.42188815,  0.48319187,  0.27948881,  0.6106914 ,
         0.65068584,  1.        ,  0.51003252,  0.31373136],
       [ 0.05295227,  0.05627586,  0.21964918,  0.03972846,  0.09714055,
         0.07326144,  0.0154035 , -0.24000385,  0.60198355,  0.49888758,
         0.24938031,  0.57511715,  0.60157965,  0.48609668,  0.63538472,
         0.62336804,  0.51003252,  1.        ,  0.4886829 ],
       [ 0.11257122,  0.14651778,  0.22000047, -0.04567498,  0.04420554,
         0.07732877,  0.0894682 , -0.24201468,  0.6508519 ,  0.76477235,
         0.28212671,  0.65210409,  0.71092403,  0.78984192,  0.40755735,
         0.54514796,  0.31373136,  0.4886829 ,  1.        ]])

### Making the T copula

In [ ]:
# before this, compute the U for each asset based on its assumed distribution

def fit_student_t_copula(U: pd.DataFrame):

    # apply inverse CDF of univariate T to each entry (column) in U
    # T = tv ^-1 (U) -> do this to each column
    T = t.ppf(U, df=2)
    # TODO -> do the T thing for many different values of v, then compute correlation and compute log likelihood. Choose one with best (highest) log likelihood
        # Correlation is done how we would usually do it
    
    # TODO -> choose a guess of v from [2, 3, 4, 5, 7, 9, 12, 16, 20, 25, 30, 36, 42, 50]
        # then compute correlation and the log likelihood
    
    # then, optimize further using scipy.optimize.minimize_scalar

    
    # return corr, df
    pass

def simulate_from_t_copula(corr, df, n_sims):
    # in order to simulate from a t copula, you take the multivariate T, simulate values, and convert them to uniform using the standard t (with fitted df)
    pass

### Using Package Copulas

In [17]:
from copulae.elliptical import StudentCopula as copulae_t
from statsmodels.distributions.copula.api import StudentTCopula as sm_t

In [18]:
# fit normal distributions
returns_np = returns.to_numpy()
means = returns_np.mean(axis=0)
stds = returns_np.std(axis=0)

In [19]:
returns_np[:, 0]

array([-0.00520157, -0.00065361, -0.00327013, ...,  0.01109839,
       -0.00492048,  0.00456443], shape=(1254,))

In [20]:
t_params_by_col = {}
Us = []
for i in range(returns_np.shape[1]):
    nu, mu, sigma = t.fit(returns_np[:, i])
    U_col = t.cdf(returns_np[:, i], loc=mu, scale=sigma, df=nu)
    Us.append(U_col)
    t_params_by_col[i] = (mu, sigma, nu)

U = np.array(Us).T

In [21]:
# U = norm.cdf(returns_np - means / stds)
# t.cdf()

In [22]:
sm_t_copula = sm_t(df=2, k_dim=19)
sm_t_copula.corr = sm_t_copula.fit_corr_param(data=U)

In [23]:
sm_t_copula.rvs(1)

array([0.65208697, 0.65042254, 0.20802524, 0.24392893, 0.73880628,
       0.64242703, 0.4331701 , 0.78384546, 0.86491794, 0.69940331,
       0.42920258, 0.35932599, 0.92225927, 0.6082398 , 0.50777844,
       0.05404165, 0.1998259 , 0.58171084, 0.12668686])

In [24]:
corrs = {}
LLs = {}
for v in range(1, 50):
    sm_t_copula = sm_t(df=v, k_dim=19)
    sm_t_copula.corr = sm_t_copula.fit_corr_param(data=U)
    LL = np.sum(sm_t_copula.logpdf(U))
    corrs[v] = sm_t_copula.corr
    LLs[v] = LL
    # print(f"LL {v}", LL)

# maximum likelihood v
df, ll = max(LLs.items(), key=lambda x: x[1])
sm_t_copula = sm_t(df=df, k_dim=19)
sm_t_copula.corr = sm_t_copula.fit_corr_param(data=U)

In [25]:
sm_t_copula.df

5

In [26]:
t_copula = copulae_t(dim=19)
t_copula.fit(U, to_pobs=False, method="ml", verbose=1000)

Optimization terminated successfully    (Exit mode 0)
            Current function value: -10394.214446174912
            Iterations: 182
            Function evaluations: 32065
            Gradient evaluations: 182

In [27]:
sm_t_copula.df - t_copula.params.df

np.float64(-7.9481275038478465)

In [ ]:
t_copula.params.df

np.float64(14.010875470701492)

In [ ]:
sm_t_copula.df

5

In [ ]:
t_copula.random(100000)

(100000, 19)

In [ ]:
t_copula.rho.shape # 19x18/2 (diagonals are assumed 1 and thus not included)
t_copula.dim

19

In [ ]:
t_copula

In [ ]:
t_copula.summary()

Student Copula Summary
================================================================================
Student Copula with 19 dimensions


Parameters
--------------------------------------------------------------------------------
 Degree of Freedom  : 14.010875470701492

 Correlation Matrix
 1.000000  0.422842  0.122781  0.036579  0.150698  0.079008  0.253870 -0.146528  0.201148  0.113494  0.222259  0.150784  0.150478  0.123797  0.067063  0.098836  0.050393  0.053664  0.111655
 0.422842  1.000000  0.142479  0.015535  0.312558  0.244392  0.912043 -0.189704  0.296145  0.150364  0.653387  0.214716  0.235722  0.164848  0.061786  0.102655  0.083114  0.055442  0.146202
 0.122781  0.142479  1.000000  0.420548  0.401445 -0.027896  0.044135 -0.950558  0.342464  0.241617  0.121017  0.233853  0.256301  0.227946  0.220292  0.264243  0.145926  0.240524  0.247260
 0.036579  0.015535  0.420548  1.000000  0.400670 -0.038389 -0.057802 -0.576951  0.045860  0.004015 -0.067814 -0.093839 -0.043016 -0.050539  0.086054  0.130828  0.110113  0.058700 -0.023679
 0.150698  0.312558  0.401445  0.400670  1.000000  0.022970  0.163111 -0.469172  0.221668  0.101968  0.144988  0.029274  0.102347  0.099505  0.104707  0.172102  0.202012  0.103353  0.056401
 0.079008  0.244392 -0.027896 -0.038389  0.022970  1.000000  0.126239  0.008692  0.098769  0.051252  0.173267  0.083259  0.071070  0.067973  0.050770  0.069118  0.062772  0.058482  0.072015
 0.253870  0.912043  0.044135 -0.057802  0.163111  0.126239  1.000000 -0.075043  0.202171  0.094909  0.645613  0.169930  0.176191  0.093355  0.011401  0.046604  0.033456  0.009933  0.081015
-0.146528 -0.189704 -0.950558 -0.576951 -0.469172  0.008692 -0.075043  1.000000 -0.383473 -0.268900 -0.149604 -0.243907 -0.277528 -0.245370 -0.250383 -0.309627 -0.189473 -0.261411 -0.272398
 0.201148  0.296145  0.342464  0.045860  0.221668  0.098769  0.202171 -0.383473  1.000000  0.595099  0.523570  0.775138  0.844041  0.592741  0.552942  0.625283  0.458373  0.600901  0.653749
 0.113494  0.150364  0.241617  0.004015  0.101968  0.051252  0.094909 -0.268900  0.595099  1.000000  0.264368  0.615587  0.639948  0.769849  0.414546  0.511508  0.327318  0.496512  0.760797
 0.222259  0.653387  0.121017 -0.067814  0.144988  0.173267  0.645613 -0.149604  0.523570  0.264368  1.000000  0.531760  0.505564  0.239519  0.228281  0.268712  0.216059  0.248324  0.274344
 0.150784  0.214716  0.233853 -0.093839  0.029274  0.083259  0.169930 -0.243907  0.775138  0.615587  0.531760  1.000000  0.836097  0.563231  0.531954  0.582148  0.434438  0.574668  0.647475
 0.150478  0.235722  0.256301 -0.043016  0.102347  0.071070  0.176191 -0.277528  0.844041  0.639948  0.505564  0.836097  1.000000  0.671791  0.544869  0.639024  0.485164  0.604750  0.709979
 0.123797  0.164848  0.227946 -0.050539  0.099505  0.067973  0.093355 -0.245370  0.592741  0.769849  0.239519  0.563231  0.671791  1.000000  0.329705  0.480554  0.276834  0.490052  0.788316
 0.067063  0.061786  0.220292  0.086054  0.104707  0.050770  0.011401 -0.250383  0.552942  0.414546  0.228281  0.531954  0.544869  0.329705  1.000000  0.608273  0.615587  0.624197  0.414780
 0.098836  0.102655  0.264243  0.130828  0.172102  0.069118  0.046604 -0.309627  0.625283  0.511508  0.268712  0.582148  0.639024  0.480554  0.608273  1.000000  0.654252  0.612077  0.547487
 0.050393  0.083114  0.145926  0.110113  0.202012  0.062772  0.033456 -0.189473  0.458373  0.327318  0.216059  0.434438  0.485164  0.276834  0.615587  0.654252  1.000000  0.505260  0.317257
 0.053664  0.055442  0.240524  0.058700  0.103353  0.058482  0.009933 -0.261411  0.600901  0.496512  0.248324  0.574668  0.604750  0.490052  0.624197  0.612077  0.505260  1.000000  0.486884
 0.111655  0.146202  0.247260 -0.023679  0.056401  0.072015  0.081015 -0.272398  0.653749  0.760797  0.274344  0.647475  0.709979  0.788316  0.414780  0.547487  0.317257  0.486884  1.000000

In [ ]:
t_copula.sigma

array([[ 1.        ,  0.42284214,  0.12278061,  0.03657923,  0.15069756,
         0.07900843,  0.25386976, -0.14652808,  0.20114831,  0.11349402,
         0.22225908,  0.1507839 ,  0.15047803,  0.12379667,  0.06706254,
         0.09883634,  0.05039278,  0.05366405,  0.11165535],
       [ 0.42284214,  1.        ,  0.14247913,  0.01553547,  0.3125583 ,
         0.2443924 ,  0.9120426 , -0.18970402,  0.29614525,  0.15036354,
         0.65338689,  0.21471595,  0.23572219,  0.16484846,  0.06178594,
         0.10265468,  0.08311378,  0.05544207,  0.14620223],
       [ 0.12278061,  0.14247913,  1.        ,  0.42054818,  0.40144542,
        -0.02789553,  0.04413494, -0.95055844,  0.34246353,  0.2416166 ,
         0.12101651,  0.23385252,  0.25630058,  0.22794578,  0.22029161,
         0.26424259,  0.1459262 ,  0.24052394,  0.24726009],
       [ 0.03657923,  0.01553547,  0.42054818,  1.        ,  0.40066984,
        -0.03838877, -0.05780186, -0.57695079,  0.04585987,  0.00401497,
        -0.06781351, -0.09383933, -0.04301585, -0.05053948,  0.08605445,
         0.13082813,  0.11011338,  0.05870034, -0.02367921],
       [ 0.15069756,  0.3125583 ,  0.40144542,  0.40066984,  1.        ,
         0.02296959,  0.16311105, -0.46917242,  0.22166826,  0.10196845,
         0.14498826,  0.02927438,  0.10234706,  0.09950488,  0.10470717,
         0.17210242,  0.20201201,  0.10335276,  0.0564014 ],
       [ 0.07900843,  0.2443924 , -0.02789553, -0.03838877,  0.02296959,
         1.        ,  0.12623872,  0.00869243,  0.09876937,  0.05125242,
         0.17326694,  0.0832585 ,  0.07107017,  0.06797317,  0.05076968,
         0.06911833,  0.06277244,  0.0584816 ,  0.07201484],
       [ 0.25386976,  0.9120426 ,  0.04413494, -0.05780186,  0.16311105,
         0.12623872,  1.        , -0.0750431 ,  0.20217144,  0.09490874,
         0.64561314,  0.16993045,  0.17619066,  0.09335457,  0.01140067,
         0.04660394,  0.03345564,  0.00993345,  0.08101489],
       [-0.14652808, -0.18970402, -0.95055844, -0.57695079, -0.46917242,
         0.00869243, -0.0750431 ,  1.        , -0.38347335, -0.26890014,
        -0.14960379, -0.24390671, -0.27752821, -0.24537028, -0.25038264,
        -0.30962738, -0.18947344, -0.26141118, -0.27239815],
       [ 0.20114831,  0.29614525,  0.34246353,  0.04585987,  0.22166826,
         0.09876937,  0.20217144, -0.38347335,  1.        ,  0.59509925,
         0.52356976,  0.7751384 ,  0.84404127,  0.5927409 ,  0.55294163,
         0.62528299,  0.45837252,  0.6009013 ,  0.65374944],
       [ 0.11349402,  0.15036354,  0.2416166 ,  0.00401497,  0.10196845,
         0.05125242,  0.09490874, -0.26890014,  0.59509925,  1.        ,
         0.26436751,  0.61558651,  0.6399479 ,  0.76984891,  0.41454617,
         0.51150811,  0.32731805,  0.49651217,  0.7607974 ],
       [ 0.22225908,  0.65338689,  0.12101651, -0.06781351,  0.14498826,
         0.17326694,  0.64561314, -0.14960379,  0.52356976,  0.26436751,
         1.        ,  0.53176004,  0.5055643 ,  0.23951917,  0.22828066,
         0.26871195,  0.21605855,  0.24832421,  0.27434375],
       [ 0.1507839 ,  0.21471595,  0.23385252, -0.09383933,  0.02927438,
         0.0832585 ,  0.16993045, -0.24390671,  0.7751384 ,  0.61558651,
         0.53176004,  1.        ,  0.83609699,  0.56323077,  0.5319544 ,
         0.58214779,  0.43443781,  0.57466794,  0.64747502],
       [ 0.15047803,  0.23572219,  0.25630058, -0.04301585,  0.10234706,
         0.07107017,  0.17619066, -0.27752821,  0.84404127,  0.6399479 ,
         0.5055643 ,  0.83609699,  1.        ,  0.67179102,  0.54486943,
         0.63902358,  0.48516378,  0.60474983,  0.70997879],
       [ 0.12379667,  0.16484846,  0.22794578, -0.05053948,  0.09950488,
         0.06797317,  0.09335457, -0.24537028,  0.5927409 ,  0.76984891,
         0.23951917,  0.56323077,  0.67179102,  1.        ,  0.32970469,
         0.48055434,  0.27683352,  0.49005152,  0.78831647],
       [ 0.06706254,  0.06178594,  0.22029161,  0.08605445,  0.10470717,
         0.05076968,  0.01140067, -0.25038264,  0.55294163,  0.41454617,
         0.22828066,  0.5319544 ,  0.54486943,  0.32970469,  1.        ,
         0.60827337,  0.61558698,  0.62419701,  0.41478001],
       [ 0.09883634,  0.10265468,  0.26424259,  0.13082813,  0.17210242,
         0.06911833,  0.04660394, -0.30962738,  0.62528299,  0.51150811,
         0.26871195,  0.58214779,  0.63902358,  0.48055434,  0.60827337,
         1.        ,  0.65425215,  0.61207701,  0.54748746],
       [ 0.05039278,  0.08311378,  0.1459262 ,  0.11011338,  0.20201201,
         0.06277244,  0.03345564, -0.18947344,  0.45837252,  0.32731805,
         0.21605855,  0.43443781,  0.48516378,  0.27683352,  0.61558698,
         0.65425215,  1.        ,  0.50525998,  0.31725714],
       [ 0.05366405,  0.05544207,  0.24052394,  0.05870034,  0.10335276,
         0.0584816 ,  0.00993345, -0.26141118,  0.6009013 ,  0.49651217,
         0.24832421,  0.57466794,  0.60474983,  0.49005152,  0.62419701,
         0.61207701,  0.50525998,  1.        ,  0.48688362],
       [ 0.11165535,  0.14620223,  0.24726009, -0.02367921,  0.0564014 ,
         0.07201484,  0.08101489, -0.27239815,  0.65374944,  0.7607974 ,
         0.27434375,  0.64747502,  0.70997879,  0.78831647,  0.41478001,
         0.54748746,  0.31725714,  0.48688362,  1.        ]])

In [ ]:
def construct_corr_from_rhos(dim, rho_array):
    upper_triangular = np.zeros((dim, dim))
    indices = np.triu_indices(dim, k=1)
    upper_triangular[indices] = rho_array
    corr = upper_triangular + upper_triangular.T + np.eye(dim)

    return corr

In [ ]:
def compute_tail_dependence(df, corr):

    def t_tail_dependence(df, rho):
        # df = degrees of freedom
        # rho = correlation between variables i,j
        arg = -np.sqrt((df + 1) * (1 - rho) / (1 + rho))
        return 2 * t.cdf(arg, df + 1)

    # Example for all pairs in a fitted copula:
    df = t_copula.params.df

    tail_dep_matrix = np.zeros_like(corr)

    for i in range(corr.shape[0]):
        for j in range(corr.shape[1]):
            tail_dep_matrix[i, j] = t_tail_dependence(df, corr[i, j])
        
    return tail_dep_matrix

In [ ]:
from numpy.linalg import eigh

# eigh(full_rho)
# eigh(t_copula.sigma)

EighResult(eigenvalues=array([0.02740576, 0.05025982, 0.11780792, 0.17946242, 0.19534363,
       0.22243164, 0.26469093, 0.29604041, 0.36413637, 0.45536438,
       0.52309736, 0.56533173, 0.75474515, 0.85358383, 0.94671051,
       1.28939898, 2.38945408, 2.53833914, 6.96639593]), eigenvectors=array([[ 6.79416655e-03, -1.24923311e-01,  3.04353742e-02,
        -1.22112111e-03,  2.33550487e-02,  5.70454472e-02,
         4.64010183e-02,  6.67068894e-02,  2.06408871e-02,
        -7.19455295e-03, -6.60872872e-02,  2.78120598e-02,
        -2.87316894e-01,  8.93161019e-01, -3.21216939e-02,
         5.90155000e-02, -5.96044432e-02,  2.66445151e-01,
         8.97268366e-02],
       [-7.53792808e-02,  7.35374547e-01, -3.59407307e-02,
        -8.81467354e-03,  6.12924083e-03, -1.59330928e-01,
        -1.39324614e-01, -9.70478364e-02, -3.27979550e-03,
        -2.63117857e-02,  1.26022687e-01, -1.78752537e-01,
         1.33215536e-01,  6.90762209e-03,  9.53516972e-03,
        -3.43272690e-02, -2.02882595e-01,  5.19609619e-01,
         1.38430955e-01],
       [-6.32583751e-01, -5.87844484e-02,  5.39578665e-02,
        -1.13187640e-02, -9.86323781e-04,  2.66131156e-02,
         2.44220150e-02,  5.71799262e-02,  4.01228644e-02,
         1.38695849e-01,  3.62431430e-01, -1.20145851e-02,
        -3.46487594e-01, -1.45816777e-01,  1.39689519e-02,
         1.86878939e-01,  4.50478338e-01,  1.69527938e-01,
         1.68269509e-01],
       [-1.62949676e-01, -1.52063964e-02, -1.84014111e-02,
        -6.87029744e-02, -2.64977756e-03, -2.85921396e-02,
        -8.88757635e-02,  4.82759186e-02, -3.87147938e-02,
        -1.19155086e-01, -7.24404178e-01, -3.58802390e-01,
         1.63181699e-01, -3.48784625e-04, -6.83868852e-02,
        -8.55299439e-02,  4.75562120e-01,  1.45966041e-01,
         4.26635729e-02],
       [-5.57887200e-03, -9.51257860e-02,  3.39328962e-02,
        -8.67948269e-02,  1.15148557e-01, -5.91347689e-03,
         1.08987296e-01, -7.14272720e-02, -8.45928689e-02,
        -1.75106220e-01,  1.13323703e-01,  6.35030940e-01,
         5.47036366e-01,  8.07494553e-02, -3.45970415e-02,
        -9.43187421e-02,  3.09345009e-01,  2.75296550e-01,
         1.03399559e-01],
       [ 1.28710848e-03, -8.95489193e-02,  2.80368053e-02,
        -1.32154577e-02, -9.85843483e-03, -2.85287197e-02,
         4.14726193e-03,  6.45043280e-03, -1.54036435e-02,
         8.10164964e-03, -5.05272654e-03,  4.89125406e-02,
        -1.32335531e-01, -1.31120568e-01, -9.49015345e-01,
        -1.33461811e-01, -1.31467055e-01,  1.20905560e-01,
         4.77351679e-02],
       [ 4.05190395e-02, -6.42708402e-01,  1.67412354e-02,
        -3.38867056e-02,  8.03099205e-03, -2.17901382e-01,
        -1.11238666e-01, -1.04901469e-01,  3.61829316e-02,
        -5.75732083e-03,  1.38751703e-01, -3.25343545e-01,
         1.50482115e-01, -1.58554113e-01,  1.58781946e-01,
        -4.47550991e-02, -2.60982001e-01,  4.82709204e-01,
         1.01833603e-01],
       [-7.50124588e-01, -5.15216919e-02,  1.69738184e-02,
        -1.39761227e-02,  6.36293807e-03, -1.12811023e-02,
         9.25528788e-03, -3.78537294e-02, -1.52354167e-02,
        -9.72079453e-02, -1.47432708e-01,  7.69220043e-02,
         2.41464317e-01,  1.20089091e-01,  1.08821998e-02,
        -1.45955785e-01, -4.77791967e-01, -1.96618800e-01,
        -1.84558727e-01],
       [-4.52092821e-02, -6.03231412e-02, -3.80187295e-01,
         5.85032645e-01, -3.51111439e-01, -1.05424100e-01,
        -2.75824539e-01, -2.03172311e-01, -1.03250129e-02,
        -5.41569275e-02, -1.84345164e-01,  2.87708684e-01,
        -1.35067041e-01, -4.81682683e-02,  5.17329575e-02,
         7.66441323e-03, -3.80326956e-02, -5.62907369e-03,
         3.33443412e-01],
       [-6.29987135e-03,  2.06005767e-02,  1.53902553e-01,
         2.70140240e-01, -2.16635258e-01, -3.23834252e-01,
         5.34013444e-01,  3.11835887e-01, -2.29753111e-01,
        -1.03260487e-02,  3.40054145e-02, -1.85606777e-01,
         2.62089192e-01,  5.24979623e-02, -7.46063883e-02,
         3.21539101e-01, -4.87457655e-02, -1.24748531e-01,
         2.86050258e-01],
       [-7.62235002e-04,  7.46021485e-03,  2.14415431e-02,
         5.58211058e-02,  1.76167704e-02,  6.08771032e-01,
         3.69471199e-01,  2.68843740e-01,  1.26890573e-03,
         3.25326449e-03, -2.52249047e-01,  1.35784843e-01,
        -1.53435965e-01, -2.70529366e-01,  1.50321132e-01,
        -9.61101894e-02, -2.52246660e-01,  3.15919902e-01,
         2.06383577e-01],
       [-7.37250774e-03,  6.34523878e-03, -3.71720810e-01,
        -4.82757316e-01,  3.01401381e-01, -4.51960381e-01,
         1.21460123e-01,  1.01872365e-01, -9.35264873e-02,
         4.21516128e-02, -2.02075316e-01,  2.16562064e-01,
        -2.58644950e-01, -9.80254297e-02,  9.15273222e-02,
         2.73883197e-02, -1.38132861e-01, -7.95187704e-02,
         3.14861665e-01],
       [ 2.50317286e-02,  2.24898656e-02,  7.73634368e-01,
        -1.64783397e-01, -1.60816030e-01, -1.04907369e-01,
        -3.09706115e-01, -5.16991028e-02,  2.64413799e-02,
         6.00924979e-02, -1.89957160e-01,  2.10593477e-01,
        -1.03139686e-01, -6.36734011e-02,  7.62244240e-02,
         4.66540950e-02, -1.08096123e-01, -8.11383754e-02,
         3.34746512e-01],
       [-7.22308660e-03, -3.26971733e-02, -2.82436510e-01,
        -4.40476329e-01, -3.64515843e-01,  3.63217960e-01,
        -2.63990980e-01,  1.09610061e-01,  1.01423172e-01,
        -2.70100926e-02,  9.59127394e-02, -9.31191178e-02,
         2.84175159e-01,  6.83931471e-02, -1.09729341e-01,
         3.93958365e-01, -7.18188349e-02, -1.20321036e-01,
         2.78182787e-01],
       [-1.35075368e-03, -9.65901526e-03,  5.15604583e-03,
        -1.32502964e-01, -9.11080552e-02,  1.84207253e-01,
         2.01907003e-02, -2.51295508e-01, -6.94601720e-01,
        -2.39152590e-01,  1.96129323e-01, -1.98901438e-01,
        -1.03393974e-01,  5.92839041e-02,  4.21030841e-02,
        -3.90023137e-01,  4.84070516e-02, -1.54465496e-01,
         2.54044726e-01],
       [-7.42268691e-03,  2.63057743e-02, -1.35864632e-02,
        -9.54252898e-02, -1.07903124e-01,  3.53853502e-02,
         4.20111600e-01, -5.48519544e-01,  4.45987451e-01,
         3.17937174e-01, -1.55765023e-02, -1.20126199e-01,
         9.61922763e-02,  8.05789098e-02, -1.33933464e-02,
        -2.52832436e-01,  5.62844108e-02, -1.34562769e-01,
         2.89677894e-01],
       [-3.57433021e-03, -6.55029471e-03, -6.05506996e-02,
         1.10727346e-01,  8.09888260e-02, -9.13074535e-03,
        -2.56476501e-01,  5.25133642e-01,  3.57489653e-02,
         4.81613142e-01,  1.29596625e-01, -4.96972789e-02,
         1.97191854e-01,  1.02223462e-01,  1.93496791e-02,
        -5.15336421e-01,  5.27756613e-02, -1.17994841e-01,
         2.26597931e-01],
       [ 7.74287578e-03,  1.49735614e-02,  4.18978539e-02,
         7.93883567e-02,  1.74736045e-01, -2.81244490e-02,
        -1.57511206e-02,  1.95829530e-01,  4.70189817e-01,
        -7.15460329e-01,  1.67719453e-01, -1.23425731e-01,
        -5.85183102e-02,  3.15157819e-03,  1.37100299e-03,
        -1.94803222e-01,  2.71763013e-02, -1.70463279e-01,
         2.72452700e-01],
       [-1.57677748e-02, -1.86711349e-02,  3.53273129e-02,
         2.61174954e-01,  7.13312809e-01,  2.27005991e-01,
        -1.56637279e-01, -2.21248136e-01, -1.05638259e-01,
         1.19711296e-01, -3.54348707e-02, -1.16999801e-01,
         1.55852759e-01,  2.46733497e-02, -8.63309493e-02,
         3.35723213e-01, -6.64213327e-02, -1.38431268e-01,
         2.95021588e-01]]))

In [ ]:
full_rho

array([[ 1.        ,  0.40685479,  0.11732062,  0.03493254,  0.14404208,
         0.07546713,  0.24308355, -0.14004949,  0.1924078 ,  0.10843706,
         0.21268109,  0.14412477,  0.14383185,  0.11829273,  0.06405202,
         0.09442021,  0.04812666,  0.05125154,  0.10667847],
       [ 0.40685479,  1.        ,  0.13617289,  0.01483543,  0.29969967,
         0.23396228,  0.90435552, -0.18142674,  0.28384163,  0.14372221,
         0.63560678,  0.20543456,  0.22562254,  0.15759748,  0.05901062,
         0.09807109,  0.07939068,  0.05295006,  0.13973749],
       [ 0.11732062,  0.13617289,  1.        ,  0.40461384,  0.38597415,
        -0.02663913,  0.04214918, -0.94591772,  0.32864814,  0.23129181,
         0.11563289,  0.22382471,  0.24542392,  0.21814622,  0.21079069,
         0.25307303,  0.1394732 ,  0.23024073,  0.23672165],
       [ 0.03493254,  0.01483543,  0.40461384,  1.        ,  0.38521817,
        -0.03666083, -0.0552044 , -0.55889007,  0.04379679,  0.00383402,
        -0.06476954, -0.08964287, -0.04108028, -0.04826679,  0.08220132,
         0.12502093,  0.10520373,  0.05606275, -0.02261251],
       [ 0.14404208,  0.29969967,  0.38597415,  0.38521817,  1.        ,
         0.02193483,  0.15593277, -0.45224109,  0.21211339,  0.09741493,
         0.13857515,  0.02795598,  0.09777695,  0.09505941,  0.10003371,
         0.16454921,  0.19323679,  0.09873859,  0.05386651],
       [ 0.07546713,  0.23396228, -0.02663913, -0.03666083,  0.02193483,
         1.        ,  0.12062929,  0.00830069,  0.09435618,  0.04894781,
         0.16566541,  0.079529  ,  0.0678813 ,  0.0649221 ,  0.04848668,
         0.06601629,  0.05995311,  0.05585377,  0.06878397],
       [ 0.24308355,  0.90435552,  0.04214918, -0.0552044 ,  0.15593277,
         0.12062929,  1.        , -0.0716777 ,  0.19338982,  0.09066522,
         0.62775799,  0.1624675 ,  0.16846807,  0.08917946,  0.0108869 ,
         0.04450752,  0.03194927,  0.00948579,  0.07738469],
       [-0.14004949, -0.18142674, -0.94591772, -0.55889007, -0.45224109,
         0.00830069, -0.0716777 ,  1.        , -0.36847173, -0.25756071,
        -0.14299466, -0.23349499, -0.26587789, -0.23490317, -0.23972681,
        -0.29686637, -0.18120555, -0.25034558, -0.26093208],
       [ 0.1924078 ,  0.28384163,  0.32864814,  0.04379679,  0.21211339,
         0.09435618,  0.19338982, -0.36847173,  1.        ,  0.57701624,
         0.50586657,  0.76011107,  0.83207415,  0.57465779,  0.53498948,
         0.60728305,  0.44163894,  0.58282241,  0.63597311],
       [ 0.10843706,  0.14372221,  0.23129181,  0.00383402,  0.09741493,
         0.04894781,  0.09066522, -0.25756071,  0.57701624,  1.        ,
         0.25319338,  0.59754306,  0.62204499,  0.75463501,  0.3987532 ,
         0.49394237,  0.31397811,  0.47914467,  0.74527937],
       [ 0.21268109,  0.63560678,  0.11563289, -0.06476954,  0.13857515,
         0.16566541,  0.62775799, -0.14299466,  0.50586657,  0.25319338,
         1.        ,  0.51397501,  0.48807356,  0.22927426,  0.21846811,
         0.25737936,  0.20672415,  0.2377457 ,  0.26280759],
       [ 0.14412477,  0.20543456,  0.22382471, -0.08964287,  0.02795598,
         0.079529  ,  0.1624675 , -0.23349499,  0.76011107,  0.59754306,
         0.51397501,  1.        ,  0.82371473,  0.54522132,  0.51416755,
         0.56407532,  0.41819128,  0.55661373,  0.62963683],
       [ 0.14383185,  0.22562254,  0.24542392, -0.04108028,  0.09777695,
         0.0678813 ,  0.16846807, -0.26587789,  0.83207415,  0.62204499,
         0.48807356,  0.82371473,  1.        ,  0.65423342,  0.52697327,
         0.62111342,  0.46796586,  0.58667673,  0.69309315],
       [ 0.11829273,  0.15759748,  0.21814622, -0.04826679,  0.09505941,
         0.0649221 ,  0.08917946, -0.23490317,  0.57465779,  0.75463501,
         0.22927426,  0.54522132,  0.65423342,  1.        ,  0.31628856,
         0.46342999,  0.26520805,  0.47277854,  0.77378285],
       [ 0.06405202,  0.05901062,  0.21079069,  0.08220132,  0.10003371,
         0.04848668,  0.0108869 , -0.23972681,  0.53498948,  0.3987532 ,
         0.21846811,  0.51416755,  0.52697327,  0.31628856,  1.        ,
         0.59020774,  0.59754353,  0.60619139,  0.39898145],
       [ 0.09442021,  0.09807109,  0.25307303,  0.12502093,  0.16454921,
         0.06601629,  0.04450752, -0.29686637,  0.60728305,  0.49394237,
         0.25737936,  0.56407532,  0.62111342,  0.46342999,  0.59020774,
         1.        ,  0.63648108,  0.5940218 ,  0.52957209],
       [ 0.04812666,  0.07939068,  0.1394732 ,  0.10520373,  0.19323679,
         0.05995311,  0.03194927, -0.18120555,  0.44163894,  0.31397811,
         0.20672415,  0.41819128,  0.46796586,  0.26520805,  0.59754353,
         0.63648108,  1.        ,  0.4877732 ,  0.30424341],
       [ 0.05125154,  0.05295006,  0.23024073,  0.05606275,  0.09873859,
         0.05585377,  0.00948579, -0.25034558,  0.58282241,  0.47914467,
         0.2377457 ,  0.55661373,  0.58667673,  0.47277854,  0.60619139,
         0.5940218 ,  0.4877732 ,  1.        ,  0.46965894],
       [ 0.10667847,  0.13973749,  0.23672165, -0.02261251,  0.05386651,
         0.06878397,  0.07738469, -0.26093208,  0.63597311,  0.74527937,
         0.26280759,  0.62963683,  0.69309315,  0.77378285,  0.39898145,
         0.52957209,  0.30424341,  0.46965894,  1.        ]])

In [ ]:
full_rho - t_copula.sigma

array([[ 0.        , -0.0159325 , -0.00588002, -0.00240428, -0.00700338,
        -0.00353599, -0.010654  ,  0.00695556, -0.00887771, -0.00529628,
        -0.00957799, -0.00673864, -0.00672082, -0.00564983, -0.00316471,
        -0.00467962, -0.00238505, -0.00256503, -0.0052391 ],
       [-0.0159325 ,  0.        , -0.007576  , -0.0022197 , -0.01319552,
        -0.01042976, -0.00778305,  0.00947084, -0.01260997, -0.00701867,
        -0.01774921, -0.00953525, -0.01031783, -0.00741732, -0.00307457,
        -0.00499898, -0.00386798, -0.00275155, -0.00687421],
       [-0.00588002, -0.007576  ,  0.        , -0.01727591, -0.01616944,
         0.00038706, -0.00308066,  0.00391916, -0.0145576 , -0.01112211,
        -0.00618896, -0.01050634, -0.01149014, -0.01030997, -0.01034889,
        -0.01223419, -0.00787768, -0.01076248, -0.01136076],
       [-0.00240428, -0.0022197 , -0.01727591,  0.        , -0.01598124,
         0.00121913,  0.00145228,  0.017966  , -0.00407506, -0.00181661,
         0.00163806,  0.00247545,  0.00019643,  0.00077388, -0.00516278,
        -0.00710989, -0.00593887, -0.00384963, -0.00062879],
       [-0.00700338, -0.01319552, -0.01616944, -0.01598124,  0.        ,
        -0.00133144, -0.00755153,  0.01728895, -0.01024311, -0.00521446,
        -0.00697814, -0.00203486, -0.00520911, -0.00487936, -0.0052872 ,
        -0.00820016, -0.00919034, -0.00507927, -0.00324013],
       [-0.00353599, -0.01042976,  0.00038706,  0.00121913, -0.00133144,
         0.        , -0.00556368,  0.00034496, -0.00465231, -0.00248037,
        -0.00766165, -0.0038453 , -0.00327125, -0.00313296, -0.00248657,
        -0.00321531, -0.00284971, -0.00280858, -0.00333129],
       [-0.010654  , -0.00778305, -0.00308066,  0.00145228, -0.00755153,
        -0.00556368,  0.        ,  0.00442884, -0.00901874, -0.00441564,
        -0.01783554, -0.00761333, -0.00787455, -0.00417069, -0.0006915 ,
        -0.00238168, -0.00158516, -0.00055598, -0.00385011],
       [ 0.00695556,  0.00947084,  0.00391916,  0.017966  ,  0.01728895,
         0.00034496,  0.00442884,  0.        ,  0.01556486,  0.0119982 ,
         0.00752539,  0.01090886,  0.01225012,  0.0109218 ,  0.01135836,
         0.0135264 ,  0.00936328,  0.0115235 ,  0.01219832],
       [-0.00887771, -0.01260997, -0.0145576 , -0.00407506, -0.01024311,
        -0.00465231, -0.00901874,  0.01556486,  0.        , -0.01808092,
        -0.017729  , -0.01500545, -0.01195657, -0.01808316, -0.01796457,
        -0.0179722 , -0.0168774 , -0.01807635, -0.01772811],
       [-0.00529628, -0.00701867, -0.01112211, -0.00181661, -0.00521446,
        -0.00248037, -0.00441564,  0.0119982 , -0.01808092,  0.        ,
        -0.01135635, -0.01803744, -0.01788317, -0.01525542, -0.0158727 ,
        -0.01762472, -0.01358867, -0.01741567, -0.01552692],
       [-0.00957799, -0.01774921, -0.00618896,  0.00163806, -0.00697814,
        -0.00766165, -0.01783554,  0.00752539, -0.017729  , -0.01135635,
         0.        , -0.01780186, -0.01751585, -0.01027574, -0.00985467,
        -0.01147559, -0.00946669, -0.01065117, -0.01167109],
       [-0.00673864, -0.00953525, -0.01050634,  0.00247545, -0.00203486,
        -0.0038453 , -0.00761333,  0.01090886, -0.01500545, -0.01803744,
        -0.01780186,  0.        , -0.01235729, -0.0180104 , -0.0178048 ,
        -0.01807611, -0.01639228, -0.01805827, -0.01783072],
       [-0.00672082, -0.01031783, -0.01149014,  0.00019643, -0.00520911,
        -0.00327125, -0.00787455,  0.01225012, -0.01195657, -0.01788317,
        -0.01751585, -0.01235729,  0.        , -0.01754962, -0.01791359,
        -0.01788389, -0.01730934, -0.01806711, -0.01684606],
       [-0.00564983, -0.00741732, -0.01030997,  0.00077388, -0.00487936,
        -0.00313296, -0.00417069,  0.0109218 , -0.01808316, -0.01525542,
        -0.01027574, -0.0180104 , -0.01754962,  0.        , -0.01343561,
        -0.01718182, -0.01189895, -0.01733964, -0.01463872],
       [-0.00316471, -0.00307457, -0.01034889, -0.00516278, -0.0052872 ,
        -0.00248657, -0.0006915 ,  0.01135836, -0.01796457, -0.0158727 ,
        -0.00985467, -0.0178048 , -0.01791359, -0.01343561,  0.        ,
        -0.01806056, -0.01802802, -0.01800512, -0.01588767],
       [-0.00467962, -0.00499898, -0.01223419, -0.00710989, -0.00820016,
        -0.00321531, -0.00238168,  0.0135264 , -0.0179722 , -0.01762472,
        -0.01147559, -0.01807611, -0.01788389, -0.01718182, -0.01806056,
         0.        , -0.01774607, -0.01805301, -0.01793974],
       [-0.00238505, -0.00386798, -0.00787768, -0.00593887, -0.00919034,
        -0.00284971, -0.00158516,  0.00936328, -0.0168774 , -0.01358867,
        -0.00946669, -0.01639228, -0.01730934, -0.01189895, -0.01802802,
        -0.01774607,  0.        , -0.01753921, -0.01330332],
       [-0.00256503, -0.00275155, -0.01076248, -0.00384963, -0.00507927,
        -0.00280858, -0.00055598,  0.0115235 , -0.01807635, -0.01741567,
        -0.01065117, -0.01805827, -0.01806711, -0.01733964, -0.01800512,
        -0.01805301, -0.01753921,  0.        , -0.01727929],
       [-0.0052391 , -0.00687421, -0.01136076, -0.00062879, -0.00324013,
        -0.00333129, -0.00385011,  0.01219832, -0.01772811, -0.01552692,
        -0.01167109, -0.01783072, -0.01684606, -0.01463872, -0.01588767,
        -0.01793974, -0.01330332, -0.01727929,  0.        ]])

In [ ]:
# t_copula.summary()

In [ ]:
dir(t_copula)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_bounds',
 '_columns',
 '_df',
 '_dim',
 '_fit_smry',
 '_force_psd',
 '_name',
 '_rhos',
 'bounds',
 'cdf',
 'dim',
 'drho',
 'dtau',
 'fit',
 'irho',
 'itau',
 'lambda_',
 'log_lik',
 'name',
 'params',
 'pdf',
 'pobs',
 'random',
 'rho',
 'sigma',
 'summary',
 'tau']

In [ ]:
pd.DataFrame(t_copula.sigma - sm_t_copula.corr)

np.float64(-0.03147638389496016)

In [ ]:
np.equal(corrs[1], corrs[20]).all()

np.True_

In [ ]:
low_tail, high_tail = sm_t_copula.dependence_tail()

In [ ]:
sm_t_copula = sm_t(df=50, k_dim=19)
sm_t_copula.corr = sm_t_copula.fit_corr_param(data=U)
sm_t_copula.corr[0]

array([ 1.        ,  0.32637347,  0.12185952,  0.03052481,  0.13780138,
        0.07492821,  0.18344942, -0.13467134,  0.26583224,  0.25870027,
        0.2221099 ,  0.12474359,  0.26596678,  0.22760942,  0.01419645,
        0.13811707,  0.12357637,  0.06147527,  0.30923474])

In [ ]:
sm_t_copula.df

10

In [ ]:
# sm_t_copula.corr - sm_t_copula.spearmans_rho()

In [ ]:
# sm_t_copula.spearmans_rho()

In [ ]:
# sm_t_copula.corr

In [ ]:
# sm_t_copula.corr

In [ ]:
sm_t_copula

array([[1.        , 0.32637347],
       [0.32637347, 1.        ]])

In [ ]:
t_copula = copulae_t()

In [ ]:
returns.to_numpy().shape

(249, 19)

In [ ]:
t_copula = copulae_t(dim=19)
t_copula.fit(returns.to_numpy(), to_pobs=True, method="ml")

In [ ]:
t_copula.params.df, t_copula.sigma.shape

(np.float64(9.726471626704669), (19, 19))

In [ ]:
sm_t_copula.df - t_copula.params.df

np.float64(39.273528373295335)

In [ ]:
t_copula.sigma - sm_t_copula.corr
sm_t_copula.df - t_copula.params.df

array([[ 0.        , -0.1274381 , -0.01511036, -0.01652867, -0.01344375,
        -0.00866895, -0.08522274,  0.03551505,  0.05134306,  0.11775149,
        -0.00279799, -0.04194926,  0.09722427,  0.1022937 , -0.03647307,
         0.06658016,  0.08775792,  0.01548735,  0.1599504 ],
       [-0.1274381 ,  0.        , -0.21730775, -0.1539832 , -0.02455612,
         0.04349179, -0.03265089,  0.24940647, -0.15742196, -0.06436268,
        -0.03265139, -0.18904887, -0.12982943,  0.01204029, -0.12349707,
        -0.02438365,  0.01779207, -0.10370022, -0.03842564],
       [-0.01511036, -0.21730775,  0.        ,  0.09985651, -0.00523925,
        -0.04458467, -0.24793068, -0.00724592, -0.16462728, -0.24098417,
        -0.17552749, -0.2466614 , -0.22053975, -0.26373857, -0.08556595,
        -0.06706415, -0.04761868, -0.1170964 , -0.25834565],
       [-0.01652867, -0.1539832 ,  0.09985651,  0.        , -0.08168139,
        -0.00076988, -0.16368871, -0.08362323, -0.04130768, -0.14987019,
        -0.04039135, -0.05535121, -0.13848336, -0.23748467,  0.00853599,
        -0.03965932, -0.06237679, -0.01366402, -0.19520988],
       [-0.01344375, -0.02455612, -0.00523925, -0.08168139,  0.        ,
         0.04445344, -0.07928206,  0.03921852, -0.12654749, -0.20322178,
        -0.14608725, -0.140771  , -0.16105368, -0.1267481 , -0.10861606,
        -0.09109363, -0.03243471, -0.08030699, -0.19018367],
       [-0.00866895,  0.04349179, -0.04458467, -0.00076988,  0.04445344,
         0.        , -0.03348772,  0.05066684, -0.11821132, -0.08080084,
        -0.07083227, -0.10299714, -0.11838774, -0.1136012 , -0.02410215,
        -0.0684474 , -0.07222662, -0.0943142 , -0.07711178],
       [-0.08522274, -0.03265089, -0.24793068, -0.16368871, -0.07928206,
        -0.03348772,  0.        ,  0.27231681, -0.18328028, -0.0819035 ,
        -0.04867689, -0.20602319, -0.14196409, -0.00055512, -0.09167111,
        -0.0066627 ,  0.0210654 , -0.08866331, -0.02953661],
       [ 0.03551505,  0.24940647, -0.00724592, -0.08362323,  0.03921852,
         0.05066684,  0.27231681,  0.        ,  0.20196234,  0.26359075,
         0.20824105,  0.26930512,  0.26300429,  0.30359973,  0.10801202,
         0.09756405,  0.07756841,  0.14154549,  0.29630647],
       [ 0.05134306, -0.15742196, -0.16462728, -0.04130768, -0.12654749,
        -0.11821132, -0.18328028,  0.20196234,  0.        , -0.03986779,
        -0.04413666, -0.05129356, -0.07299316, -0.07724167, -0.07618509,
         0.05358585, -0.03414555,  0.00499531, -0.00885343],
       [ 0.11775149, -0.06436268, -0.24098417, -0.14987019, -0.20322178,
        -0.08080084, -0.0819035 ,  0.26359075, -0.03986779,  0.        ,
         0.03053822,  0.08515753,  0.02484084, -0.10427687, -0.17714291,
        -0.08854817, -0.01392723, -0.13759465, -0.02175938],
       [-0.00279799, -0.03265139, -0.17552749, -0.04039135, -0.14608725,
        -0.07083227, -0.04867689,  0.20824105, -0.04413666,  0.03053822,
         0.        , -0.12336807, -0.05042113,  0.09046824,  0.00122549,
         0.14205866,  0.08789757,  0.03395631,  0.08200437],
       [-0.04194926, -0.18904887, -0.2466614 , -0.05535121, -0.140771  ,
        -0.10299714, -0.20602319,  0.26930512, -0.05129356,  0.08515753,
        -0.12336807,  0.        , -0.03161005,  0.02255919, -0.06513892,
         0.04564458,  0.07664036, -0.0156099 ,  0.06139547],
       [ 0.09722427, -0.12982943, -0.22053975, -0.13848336, -0.16105368,
        -0.11838774, -0.14196409,  0.26300429, -0.07299316,  0.02484084,
        -0.05042113, -0.03161005,  0.        ,  0.04200715, -0.21257758,
        -0.03528001,  0.00719142, -0.07930572,  0.03577384],
       [ 0.1022937 ,  0.01204029, -0.26373857, -0.23748467, -0.1267481 ,
        -0.1136012 , -0.00055512,  0.30359973, -0.07724167, -0.10427687,
         0.09046824,  0.02255919,  0.04200715,  0.        , -0.3807102 ,
        -0.20754724,  0.03324943, -0.25503571, -0.07170743],
       [-0.03647307, -0.12349707, -0.08556595,  0.00853599, -0.10861606,
        -0.02410215, -0.09167111,  0.10801202, -0.07618509, -0.17714291,
         0.00122549, -0.06513892, -0.21257758, -0.3807102 ,  0.        ,
         0.0195194 , -0.15442513, -0.12976952, -0.17827793],
       [ 0.06658016, -0.02438365, -0.06706415, -0.03965932, -0.09109363,
        -0.0684474 , -0.0066627 ,  0.09756405,  0.05358585, -0.08854817,
         0.14205866,  0.04564458, -0.03528001, -0.20754724,  0.0195194 ,
         0.        , -0.0391296 , -0.00108477, -0.07853461],
       [ 0.08775792,  0.01779207, -0.04761868, -0.06237679, -0.03243471,
        -0.07222662,  0.0210654 ,  0.07756841, -0.03414555, -0.01392723,
         0.08789757,  0.07664036,  0.00719142,  0.03324943, -0.15442513,
        -0.0391296 ,  0.        , -0.12481615, -0.01013665],
       [ 0.01548735, -0.10370022, -0.1170964 , -0.01366402, -0.08030699,
        -0.0943142 , -0.08866331,  0.14154549,  0.00499531, -0.13759465,
         0.03395631, -0.0156099 , -0.07930572, -0.25503571, -0.12976952,
        -0.00108477, -0.12481615,  0.        , -0.10286434],
       [ 0.1599504 , -0.03842564, -0.25834565, -0.19520988, -0.19018367,
        -0.07711178, -0.02953661,  0.29630647, -0.00885343, -0.02175938,
         0.08200437,  0.06139547,  0.03577384, -0.07170743, -0.17827793,
        -0.07853461, -0.01013665, -0.10286434,  0.        ]])

In [ ]:
for column in returns:
    data = returns[column]